dataset_name: clue
batch_size: 6
learning_rate: 0.001
save_figure: 0
t_start: 0
t_end: 3000
t_valid: 3000  # How long is the actual sample, the rest is "resting time"
t_s: 1
input_x: 64
input_y: 1
input_channels: 1
num_classes: 1
dynamic_des_spike: 0

output_dim: 2
lamda: 2   # firing rate in gerenrating Poisson datasets
time_unit: 0.001
#calculate_spike_num_loss: 1
#calculate_classification_loss: 0
get_gradient: 0  # get the gradient of internal variables
tao_m: 1
tao_s: 0.2

#get_spike_c: 1

#target_spike_time: 5
#
#dynamic_des_spike: 0
#dynamic_rate: 0.8  # theta_m = 0.8*theta

# Spike response parameters
sr_params: {mult: 1, tau: 1, epsilon: 0.01}
# Activation function parameters
af_params: {theta: 10, sigma : [0, 0, 0, 0], wScale : [0.5, 1, 1, 0]}

ref_params: {mult: -20, tau: 5, epsilon: -0.001}

pdf_params: {scale: 1, tau: 4.3429}